// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildFailed(arg1:string,arg2:string):Promise<any>;

export function BuildSucess(arg1:any):Promise<any>;

export function InitEsClient(arg1:string,arg2:string,arg3:string):Promise<any>;
