// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildFailed(arg1, arg2) {
  return window['go']['service']['Connection']['BuildFailed'](arg1, arg2);
}

export function BuildSucess(arg1) {
  return window['go']['service']['Connection']['BuildSucess'](arg1);
}

export function CreateEsConnection(arg1) {
  return window['go']['service']['Connection']['CreateEsConnection'](arg1);
}

export function GetSavedConnectionList() {
  return window['go']['service']['Connection']['GetSavedConnectionList']();
}

export function Init(arg1) {
  return window['go']['service']['Connection']['Init'](arg1);
}

export function InitEsClient(arg1, arg2, arg3) {
  return window['go']['service']['Connection']['InitEsClient'](arg1, arg2, arg3);
}

export function TestEsConnection(arg1) {
  return window['go']['service']['Connection']['TestEsConnection'](arg1);
}
