// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function BuildFailed(arg1:string,arg2:string):Promise<models.BaseResponse>;

export function BuildSucess(arg1:any):Promise<models.BaseResponse>;

export function CreateEsConnection(arg1:models.NewConnectionReq):Promise<models.BaseResponse>;

export function GetSavedConnectionList():Promise<models.BaseResponse>;

export function Init(arg1:models.EdmContext):Promise<Error>;

export function TestEsConnection(arg1:models.NewConnectionReq):Promise<models.BaseResponse>;
