// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildFailed(arg1, arg2) {
  return window['go']['service']['Record']['BuildFailed'](arg1, arg2);
}

export function BuildSucess(arg1) {
  return window['go']['service']['Record']['BuildSucess'](arg1);
}

export function Init(arg1) {
  return window['go']['service']['Record']['Init'](arg1);
}

export function InitEsClient(arg1, arg2, arg3) {
  return window['go']['service']['Record']['InitEsClient'](arg1, arg2, arg3);
}

export function Search(arg1) {
  return window['go']['service']['Record']['Search'](arg1);
}
