// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {elastic} from '../models';

export function CreateEsConnection(arg1:models.NewConnectionReq):Promise<string>;

export function GetEsClient(arg1:string):Promise<elastic.Client>;

export function Init(arg1:models.EdmContext):Promise<Error>;

export function TestEsConnection(arg1:models.NewConnectionReq):Promise<string>;
