// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEsConnection(arg1) {
  return window['go']['connection']['Connection']['CreateEsConnection'](arg1);
}

export function GetEsClient(arg1) {
  return window['go']['connection']['Connection']['GetEsClient'](arg1);
}

export function Init(arg1) {
  return window['go']['connection']['Connection']['Init'](arg1);
}

export function TestEsConnection(arg1) {
  return window['go']['connection']['Connection']['TestEsConnection'](arg1);
}
